services:
  fetchardy:
    build: .
    ports:
      - 10002:80
    restart: always
    volumes:
      - games:/games
      - media:/media
    networks:
      - otel

networks:
  otel:
    name: otel
    external: true

volumes:
  games:
    external: true
  media:
    external: true
